name: Build

on:
  pull_request:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout obs-studio
      uses: actions/checkout@v2
      with:
        repository: obsproject/obs-studio
        path: obs-studio
        submodules: recursive
        ref: 25.0.8

    - name: Checkout obs-mac-virtualcam
      uses: actions/checkout@v2
      with:
        path: obs-mac-virtualcam

    - name: Install OBS deps
      run: |
        brew bundle --file=obs-mac-virtualcam/Brewfile

    - name: Build OBS
      run: |
        mkdir obs-studio/build
        cd obs-studio/build

        export QTDIR=$(brew --prefix qt5)
        cmake ..
        make -j

    - name: Build the plugin
      run: |
        mkdir obs-mac-virtualcam/build
        cd obs-mac-virtualcam/build

        cmake -DLIBOBS_INCLUDE_DIR:STRING=$GITHUB_WORKSPACE/obs-studio/libobs \
          -DLIBOBS_LIB:STRING=$GITHUB_WORKSPACE/obs-studio/build/libobs/libobs.dylib \
          -DOBS_FRONTEND_LIB:STRING=$GITHUB_WORKSPACE/obs-studio/build/UI/obs-frontend-api/libobs-frontend-api.dylib \
          -DQTDIR:STRING=/usr/local/opt/qt ..
        make -j
